### ISSUE TITLE
How should I use the modify_func function to edit Gaussians?

### ISSUE THREAD

**Issue by iambrc** [gmum/VeGaS#3]
How should I use `modify_func` to edit certain objects in the video as shown on the website `https://gmum.github.io/VeGaS/` ?
Are there any examples? Thanks!

```python
def modify_func(means3D: torch.Tensor, # num_gauss x 3, means3D[:,1] = 0
                scales: torch.Tensor, # num_gauss x 3, scales[:,1] = eps
                rotations: torch.Tensor # # num_gauss x 4, 3D quaternions of 2D rotations
                time: float):
    return means3D, scales, rotations
```

**Comment by adreamwu** [comment]
same question. Could you tell me how to edit it?

**Comment by adreamwu** [comment]
> How should I use `modify_func` to edit certain objects in the video as shown on the website `https://gmum.github.io/VeGaS/` ? Are there any examples? Thanks!
> 
> def modify_func(means3D: torch.Tensor, # num_gauss x 3, means3D[:,1] = 0
>                 scales: torch.Tensor, # num_gauss x 3, scales[:,1] = eps
>                 rotations: torch.Tensor # # num_gauss x 4, 3D quaternions of 2D rotations
>                 time: float):
>     return means3D, scales, rotations

@iambrc same question. How can we select certain objects and edit them?
